on:
  email:
    imap:
      host: outlook.office365.com
      port: 993
      tls: true
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
    config:
      filterOutputs:
        # subject: send2kindle_by_workflow
        subject: 1
        text: 1
      # filter:
        # subject:
          # $regex: send2kindle_by_workflow
jobs:
  send_email:
    name: Send Email
    runs-on: ubuntu-latest
    steps:
      # - name: Print Outputs
        # env:
          # subject: ${{(on.email.outputs.subject)}}
        # run: |
          # echo subject: $subject

      # - name: Print Base64 Outputs
        # env:
          # subject: ${{(on.email.outputs.subject)}}
          # output: ${{(on.email.outputs.text)}}
        # run: |
          # echo "output=$(echo $output| base64)" >> $GITHUB_ENV

      # - name: Send mail
      #   uses: muxueqz/action-send-mail@v3.0.3
      #   with:
      #     server_address: outlook.office365.com
      #     server_port: 587
      #     username: ${{secrets.EMAIL_USER}}
      #     password: ${{secrets.EMAIL_PASSWORD}}
      #     subject: ${{(on.email.outputs.subject)}}
      #     body: Build job of ${{github.repository}} completed successfully!
      #     to: ${{secrets.TO_EMAIL}}
      #     from: actionsworkflow # <user@example.com>
      #     #          # Optional content type (defaults to text/plain):
      #     #          content_type: text/html
      #     #          # Optional converting Markdown to HTML (set content_type to text/html too):
      #     #          convert_markdown: true
      #     #          # Optional attachments:
      #     #          attachments: attachments.zip,git.diff,./dist/static/main.js
      #     # attachments: '[{"content": "test attachments", "filename":"push.txt"}]'
      #     # content_type: text/html
      #     # attachments: ${{(on.email.outputs.textAsHtml)}}
      #     # attachments: '[${{(on.email.outputs.text)}}]'
      #     attachments: ${{(on.email.outputs.text)}}
      #     # attachments: ${{(output)}}
      - name: Send Email by Docker
        uses: muxueqz/sendemail-alpine@main
        #        # env:
        #          SUBJECT: ${{(on.email.outputs.subject)}}
        #          SMTP_SERVER: outlook.office365.com:587
        #          TO_ADDRESS: ${{secrets.TO_EMAIL}}
        #          FROM_ADDRESS: ${{secrets.EMAIL_USER}}
        #          SMTP_USER: ${{secrets.EMAIL_USER}}
        #          SMTP_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
        #          BODY: From Docker
        #          # ATTACHMENTS: ${{(on.email.outputs.text)}}
        #          ATTACHMENTS: test ATTACHMENTS
        #          ATTACHMENTS_FILENAME: ${{(on.email.outputs.subject)}}.txt
        #        # run: |
        #          # /usr/bin/sendemail.sh
        with:
          subject: ${{(on.email.outputs.subject)}}
          smtp_server: outlook.office365.com:587
          to_address: ${{secrets.TO_EMAIL}}
          from_address: ${{secrets.EMAIL_USER}}
          smtp_user: ${{secrets.EMAIL_USER}}
          smtp_password: ${{secrets.EMAIL_PASSWORD}}
          body: From Docker
          ATTACHMENTS: ${{(on.email.outputs.text)}}
          # attachments: TEST atTACHMENTS
          attachments_filename: ${{(on.email.outputs.subject)}}.txt
          # entrypoint: /usr/bin/sendemail.sh

          #  send_email:
          #    name: Send Email
          #    runs-on: ubuntu-latest
          #    steps:
          #      - name: Send Email by Docker
          #        uses: docker://muxueqz/sendemail-alpine
          #        env:
          #          SUBJECT: ${{(on.email.outputs.subject)}}
          #          SMTP_SERVER: outlook.office365.com:587
          #          TO_ADDRESS: ${{secrets.TO_EMAIL}}
          #          FROM_ADDRESS: ${{secrets.EMAIL_USER}}
          #          SMTP_USER: ${{secrets.EMAIL_USER}}
          #          SMTP_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          #          BODY: From Docker
          #          ATTACHMENTS: ${{(on.email.outputs.text)}}
          #          ATTACHMENTS_FILENAME: ${{(on.email.outputs.subject)}}.txt
          #        # run: |
          #          # /usr/bin/sendemail.sh
          #        with:
          #          entrypoint: /usr/bin/sendemail.sh
