on:
  email:
    imap:
      host: outlook.office365.com
      port: 993
      tls: true
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
    # config:
      # filterOutputs:
        # subject: send2kindle_by_workflow
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{(on.email.outputs.subject)}}
        run: |
          echo subject: $subject

      - name: Send mail
        uses: muxueqz/action-send-mail@v2
        with:
          server_address: outlook.office365.com
          server_port: 465
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Github Actions job result
          body: Build job of ${{github.repository}} completed successfully!
          to: zhangmingyuan240@gmail.com
          from: actionsworkflow # <user@example.com>
          #          # Optional content type (defaults to text/plain):
          #          content_type: text/html
          #          # Optional converting Markdown to HTML (set content_type to text/html too):
          #          convert_markdown: true
          #          # Optional attachments:
          #          attachments: attachments.zip,git.diff,./dist/static/main.js
