on:
  script:
    run: |
      return [{
        id: Date.now(),
        title: 'run'
      }]
    # run: |
      # const result = await helpers.axios.get("https://jsonplaceholder.typicode.com/posts")
      # return result.data
      # return {id: 199}
      # const id = helpers.createContentDigest({ title: "value" });
      # return
    deduplicationKey: id
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Get UnRead Email
        uses: muxueqz/getemail-action@main
        with:
          email_server: outlook.office365.com
          email_user: ${{secrets.EMAIL_USER}}
          email_password: ${{secrets.EMAIL_PASSWORD}}
          output_file: './outputs/'
      - name: Make convert script
        # uses: maxheld83/pandoc@v2
        # uses: docker://pandoc/core:latest
        # with:
          # entrypoint: /bin/echo
          # args: 'for i in ./outputs/*.html;do pandoc --output="$i.docx" "$i"' > outputs/convert.sh
        # run: echo 'for i in ./outputs/*.html;do [[ -r "$i" ]] && pandoc --output="$i.docx" "$i" ;done ; exit 0' > outputs/convert.sh
        run: echo 'find /tmp/mozilla_muxueqz0/ -maxdepth 1 -name "*.html" ! -name "Microsoft 帐户异常登录活动*" -exec pandoc --output="{}.docx" "{}" ; exit 0' > outputs/convert.sh
      - name: Convert via Pandoc
        # uses: maxheld83/pandoc@v2
        uses: docker://pandoc/core:latest
        with:
          entrypoint: /bin/sh
          args: ./outputs/convert.sh
        # run: for i in ./outputs/*.html;do pandoc --output='"$i.docx"' '"$i"'
        # run: for i in ./outputs/*.html; do pandoc --output="$i.docx" "$i"; done
          # args: for i in ./outputs/*.html;do pandoc --output='"$i.docx"' '"$i"'
      # - name: Print Pandoc Outputs
        # run: wc -c ./outputs/*.docx
      - name: Send mail by action-send-mail
        uses: muxueqz/sendemail-alpine@main
        # uses: dawidd6/action-send-mail@v2
        with:
          smtp_server: outlook.office365.com:587
          server_port: 587
          smtp_user: ${{secrets.EMAIL_USER}}
          smtp_password: ${{secrets.EMAIL_PASSWORD}}
          # subject: ${{(on.email.outputs.subject)}}
          subject: "send to kindle"
          body: Build job of ${{github.repository}} completed successfully!
          to_address: ${{secrets.TO_EMAIL}}
          from_address: ${{secrets.EMAIL_USER}}
          attachments: "./outputs/"
      - name: Set Read Email
        uses: muxueqz/email-mark-read-action@main
        with:
          email_server: outlook.office365.com
          email_user: ${{secrets.EMAIL_USER}}
          email_password: ${{secrets.EMAIL_PASSWORD}}
          output_file: './outputs/'
