on:
  email:
    imap:
      host: outlook.office365.com
      port: 993
      tls: true
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
      #    config:
      #      # filterOutputs:
      #        # subject: send2kindle_by_workflow
      #      filter:
      #        subject: 
      #          $regex: send2kindle_by_workflow
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{(on.email.outputs.subject)}}
        run: |
          echo subject: $subject

      - name: Send mail
        uses: muxueqz/action-send-mail@v3.0.3
        with:
          server_address: outlook.office365.com
          server_port: 587
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: ${{(on.email.outputs.subject)}}
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{secrets.TO_EMAIL}}
          from: actionsworkflow # <user@example.com>
          #          # Optional content type (defaults to text/plain):
          #          content_type: text/html
          #          # Optional converting Markdown to HTML (set content_type to text/html too):
          #          convert_markdown: true
          #          # Optional attachments:
          #          attachments: attachments.zip,git.diff,./dist/static/main.js
          # attachments: '[{"content": "test attachments", "filename":"push.txt"}]'
          content_type: text/html
          attachments: ${{(on.email.outputs.textAsHtml)}}
          # attachments: '[${{(on.email.outputs.text)}}]'
          # attachments: ${{(on.email.outputs.text)}}
