on:
  email:
    imap:
      host: outlook.office365.com
      port: 993
      tls: true
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
    config:
      # force: 1
      # limit: 1
      filterOutputs:
        subject: 1
        messageId: 1
jobs:
  send_email:
    name: Send Email
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          subject: ${{(on.email.outputs.subject)}}
          message_id: ${{(on.email.outputs.messageId)}}
        run: |
          echo subject: $subject
          echo message_id: $message_id
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Get Email by Message ID
        uses: muxueqz/getemail-action@main
        with:
          email_server: outlook.office365.com
          email_user: ${{secrets.EMAIL_USER}}
          email_password: ${{secrets.EMAIL_PASSWORD}}
          output_file: input.html
          message_id: ${{(on.email.outputs.messageId)}}
      - name: Convert via Pandoc
        # uses: maxheld83/pandoc@v2
        uses: docker://pandoc/core:latest
        with:
          args: "pandoc --output=${{(on.email.outputs.subject)}}.docx input.html"
      - name: Print Pandoc Outputs
        # run: wc -c index.docx
        run: wc -c "${{(on.email.outputs.subject)}}.docx"
      - name: Send mail by action-send-mail
        # uses: muxueqz/action-send-mail@v3.0.4
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: outlook.office365.com
          server_port: 587
          username: ${{secrets.EMAIL_USER}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: ${{(on.email.outputs.subject)}}
          body: Build job of ${{github.repository}} completed successfully!
          to: ${{secrets.TO_EMAIL}}
          from: actionsworkflow # <user@example.com>
          attachments: "${{(on.email.outputs.subject)}}.docx"
