name: Document Conversion

on:
  email:
    imap:
      host: outlook.office365.com
      port: 993
      tls: true
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
    config:
      filterOutputs:
        # subject: send2kindle_by_workflow
        subject: 1
        text: 1
        textAsHtml: 1
        html: 1

jobs:
  convert_via_pandoc:
    name: Convert via Pandoc
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: maxheld83/pandoc@v2
        with:
          args: "--help"
