name: Check IMAP email and add to Pocket

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - main

jobs:
  check-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pocket
      - name: Check email and add to Pocket
        env:
          IMAP_SERVER: ${{secrets.IMAP_SERVER}}
          IMAP_USERNAME: ${{secrets.EMAIL_USER}}
          IMAP_PASSWORD: ${{secrets.EMAIL_PASSWORD}}
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
          POCKET_RECIPIENT_EMAIL: ${{ secrets.ADD2POCKET_EMAIL }}
        run: |
          python3 check_email_and_add_to_pocket.py
